// Code generated by schemagen. DO NOT EDIT.
//
// Generated from CS2 entity schema definitions.
// Schema system approach inspired by CounterStrikeSharp
// (github.com/roflmuffin/CounterStrikeSharp).

package entities

import (
	"github.com/corrreia/gostrike/pkg/gostrike"
)


// CBaseEntity wraps an Entity with typed accessors for CBaseEntity schema fields.
type CBaseEntity struct {
	*gostrike.Entity
}

// NewCBaseEntity wraps an existing Entity as a CBaseEntity.
// Returns nil if the entity is nil.
func NewCBaseEntity(e *gostrike.Entity) *CBaseEntity {
	if e == nil {
		return nil
	}
	return &CBaseEntity{Entity: e}
}

// MoveType returns the CBaseEntity::m_MoveType property.
func (e *CBaseEntity) MoveType() int32 {
	v, _ := e.GetPropInt("CBaseEntity", "m_MoveType")
	return v
}

// SetMoveType sets the CBaseEntity::m_MoveType property.
func (e *CBaseEntity) SetMoveType(v int32) {
	e.SetPropInt("CBaseEntity", "m_MoveType", v)
}

// AbsRotation returns the CBaseEntity::m_angAbsRotation property.
func (e *CBaseEntity) AbsRotation() gostrike.Vector3 {
	v, _ := e.GetPropVector("CBaseEntity", "m_angAbsRotation")
	return v
}

// SetAbsRotation sets the CBaseEntity::m_angAbsRotation property.
func (e *CBaseEntity) SetAbsRotation(v gostrike.Vector3) {
	e.SetPropVector("CBaseEntity", "m_angAbsRotation", v)
}

// TakesDamage returns the CBaseEntity::m_bTakesDamage property.
func (e *CBaseEntity) TakesDamage() bool {
	v, _ := e.GetPropBool("CBaseEntity", "m_bTakesDamage")
	return v
}

// SetTakesDamage sets the CBaseEntity::m_bTakesDamage property.
func (e *CBaseEntity) SetTakesDamage(v bool) {
	e.SetPropBool("CBaseEntity", "m_bTakesDamage", v)
}

// FFlags returns the CBaseEntity::m_fFlags property.
func (e *CBaseEntity) FFlags() int32 {
	v, _ := e.GetPropInt("CBaseEntity", "m_fFlags")
	return v
}

// SetFFlags sets the CBaseEntity::m_fFlags property.
func (e *CBaseEntity) SetFFlags(v int32) {
	e.SetPropInt("CBaseEntity", "m_fFlags", v)
}

// SimulationTime returns the CBaseEntity::m_flSimulationTime property.
func (e *CBaseEntity) SimulationTime() float32 {
	v, _ := e.GetPropFloat("CBaseEntity", "m_flSimulationTime")
	return v
}

// SetSimulationTime sets the CBaseEntity::m_flSimulationTime property.
func (e *CBaseEntity) SetSimulationTime(v float32) {
	e.SetPropFloat("CBaseEntity", "m_flSimulationTime", v)
}

// Health returns the CBaseEntity::m_iHealth property.
func (e *CBaseEntity) Health() int32 {
	v, _ := e.GetPropInt("CBaseEntity", "m_iHealth")
	return v
}

// SetHealth sets the CBaseEntity::m_iHealth property.
func (e *CBaseEntity) SetHealth(v int32) {
	e.SetPropInt("CBaseEntity", "m_iHealth", v)
}

// MaxHealth returns the CBaseEntity::m_iMaxHealth property.
func (e *CBaseEntity) MaxHealth() int32 {
	v, _ := e.GetPropInt("CBaseEntity", "m_iMaxHealth")
	return v
}

// SetMaxHealth sets the CBaseEntity::m_iMaxHealth property.
func (e *CBaseEntity) SetMaxHealth(v int32) {
	e.SetPropInt("CBaseEntity", "m_iMaxHealth", v)
}

// TeamNum returns the CBaseEntity::m_iTeamNum property.
func (e *CBaseEntity) TeamNum() int32 {
	v, _ := e.GetPropInt("CBaseEntity", "m_iTeamNum")
	return v
}

// SetTeamNum sets the CBaseEntity::m_iTeamNum property.
func (e *CBaseEntity) SetTeamNum(v int32) {
	e.SetPropInt("CBaseEntity", "m_iTeamNum", v)
}

// LifeState returns the CBaseEntity::m_lifeState property.
func (e *CBaseEntity) LifeState() int32 {
	v, _ := e.GetPropInt("CBaseEntity", "m_lifeState")
	return v
}

// SetLifeState sets the CBaseEntity::m_lifeState property.
func (e *CBaseEntity) SetLifeState(v int32) {
	e.SetPropInt("CBaseEntity", "m_lifeState", v)
}

// SubclassID returns the CBaseEntity::m_nSubclassID property.
func (e *CBaseEntity) SubclassID() int32 {
	v, _ := e.GetPropInt("CBaseEntity", "m_nSubclassID")
	return v
}

// SetSubclassID sets the CBaseEntity::m_nSubclassID property.
func (e *CBaseEntity) SetSubclassID(v int32) {
	e.SetPropInt("CBaseEntity", "m_nSubclassID", v)
}

// AbsOrigin returns the CBaseEntity::m_vecAbsOrigin property.
func (e *CBaseEntity) AbsOrigin() gostrike.Vector3 {
	v, _ := e.GetPropVector("CBaseEntity", "m_vecAbsOrigin")
	return v
}

// SetAbsOrigin sets the CBaseEntity::m_vecAbsOrigin property.
func (e *CBaseEntity) SetAbsOrigin(v gostrike.Vector3) {
	e.SetPropVector("CBaseEntity", "m_vecAbsOrigin", v)
}

// AbsVelocity returns the CBaseEntity::m_vecAbsVelocity property.
func (e *CBaseEntity) AbsVelocity() gostrike.Vector3 {
	v, _ := e.GetPropVector("CBaseEntity", "m_vecAbsVelocity")
	return v
}

// SetAbsVelocity sets the CBaseEntity::m_vecAbsVelocity property.
func (e *CBaseEntity) SetAbsVelocity(v gostrike.Vector3) {
	e.SetPropVector("CBaseEntity", "m_vecAbsVelocity", v)
}

// CBasePlayerPawn wraps an Entity with typed accessors for CBasePlayerPawn schema fields.
type CBasePlayerPawn struct {
	*gostrike.Entity
}

// NewCBasePlayerPawn wraps an existing Entity as a CBasePlayerPawn.
// Returns nil if the entity is nil.
func NewCBasePlayerPawn(e *gostrike.Entity) *CBasePlayerPawn {
	if e == nil {
		return nil
	}
	return &CBasePlayerPawn{Entity: e}
}

// CameraServices returns the CBasePlayerPawn::m_pCameraServices property.
func (e *CBasePlayerPawn) CameraServices() int32 {
	v, _ := e.GetPropInt("CBasePlayerPawn", "m_pCameraServices")
	return v
}

// SetCameraServices sets the CBasePlayerPawn::m_pCameraServices property.
func (e *CBasePlayerPawn) SetCameraServices(v int32) {
	e.SetPropInt("CBasePlayerPawn", "m_pCameraServices", v)
}

// ItemServices returns the CBasePlayerPawn::m_pItemServices property.
func (e *CBasePlayerPawn) ItemServices() int32 {
	v, _ := e.GetPropInt("CBasePlayerPawn", "m_pItemServices")
	return v
}

// SetItemServices sets the CBasePlayerPawn::m_pItemServices property.
func (e *CBasePlayerPawn) SetItemServices(v int32) {
	e.SetPropInt("CBasePlayerPawn", "m_pItemServices", v)
}

// MovementServices returns the CBasePlayerPawn::m_pMovementServices property.
func (e *CBasePlayerPawn) MovementServices() int32 {
	v, _ := e.GetPropInt("CBasePlayerPawn", "m_pMovementServices")
	return v
}

// SetMovementServices sets the CBasePlayerPawn::m_pMovementServices property.
func (e *CBasePlayerPawn) SetMovementServices(v int32) {
	e.SetPropInt("CBasePlayerPawn", "m_pMovementServices", v)
}

// WeaponServices returns the CBasePlayerPawn::m_pWeaponServices property.
func (e *CBasePlayerPawn) WeaponServices() int32 {
	v, _ := e.GetPropInt("CBasePlayerPawn", "m_pWeaponServices")
	return v
}

// SetWeaponServices sets the CBasePlayerPawn::m_pWeaponServices property.
func (e *CBasePlayerPawn) SetWeaponServices(v int32) {
	e.SetPropInt("CBasePlayerPawn", "m_pWeaponServices", v)
}

// CBasePlayerWeapon wraps an Entity with typed accessors for CBasePlayerWeapon schema fields.
type CBasePlayerWeapon struct {
	*gostrike.Entity
}

// NewCBasePlayerWeapon wraps an existing Entity as a CBasePlayerWeapon.
// Returns nil if the entity is nil.
func NewCBasePlayerWeapon(e *gostrike.Entity) *CBasePlayerWeapon {
	if e == nil {
		return nil
	}
	return &CBasePlayerWeapon{Entity: e}
}

// NextPrimaryAttackTickRatio returns the CBasePlayerWeapon::m_flNextPrimaryAttackTickRatio property.
func (e *CBasePlayerWeapon) NextPrimaryAttackTickRatio() float32 {
	v, _ := e.GetPropFloat("CBasePlayerWeapon", "m_flNextPrimaryAttackTickRatio")
	return v
}

// SetNextPrimaryAttackTickRatio sets the CBasePlayerWeapon::m_flNextPrimaryAttackTickRatio property.
func (e *CBasePlayerWeapon) SetNextPrimaryAttackTickRatio(v float32) {
	e.SetPropFloat("CBasePlayerWeapon", "m_flNextPrimaryAttackTickRatio", v)
}

// NextSecondaryAttackTickRatio returns the CBasePlayerWeapon::m_flNextSecondaryAttackTickRatio property.
func (e *CBasePlayerWeapon) NextSecondaryAttackTickRatio() float32 {
	v, _ := e.GetPropFloat("CBasePlayerWeapon", "m_flNextSecondaryAttackTickRatio")
	return v
}

// SetNextSecondaryAttackTickRatio sets the CBasePlayerWeapon::m_flNextSecondaryAttackTickRatio property.
func (e *CBasePlayerWeapon) SetNextSecondaryAttackTickRatio(v float32) {
	e.SetPropFloat("CBasePlayerWeapon", "m_flNextSecondaryAttackTickRatio", v)
}

// Clip1 returns the CBasePlayerWeapon::m_iClip1 property.
func (e *CBasePlayerWeapon) Clip1() int32 {
	v, _ := e.GetPropInt("CBasePlayerWeapon", "m_iClip1")
	return v
}

// SetClip1 sets the CBasePlayerWeapon::m_iClip1 property.
func (e *CBasePlayerWeapon) SetClip1(v int32) {
	e.SetPropInt("CBasePlayerWeapon", "m_iClip1", v)
}

// Clip2 returns the CBasePlayerWeapon::m_iClip2 property.
func (e *CBasePlayerWeapon) Clip2() int32 {
	v, _ := e.GetPropInt("CBasePlayerWeapon", "m_iClip2")
	return v
}

// SetClip2 sets the CBasePlayerWeapon::m_iClip2 property.
func (e *CBasePlayerWeapon) SetClip2(v int32) {
	e.SetPropInt("CBasePlayerWeapon", "m_iClip2", v)
}

// NextThinkTick returns the CBasePlayerWeapon::m_nNextThinkTick property.
func (e *CBasePlayerWeapon) NextThinkTick() int32 {
	v, _ := e.GetPropInt("CBasePlayerWeapon", "m_nNextThinkTick")
	return v
}

// SetNextThinkTick sets the CBasePlayerWeapon::m_nNextThinkTick property.
func (e *CBasePlayerWeapon) SetNextThinkTick(v int32) {
	e.SetPropInt("CBasePlayerWeapon", "m_nNextThinkTick", v)
}

// CCSGameRules wraps an Entity with typed accessors for CCSGameRules schema fields.
type CCSGameRules struct {
	*gostrike.Entity
}

// NewCCSGameRules wraps an existing Entity as a CCSGameRules.
// Returns nil if the entity is nil.
func NewCCSGameRules(e *gostrike.Entity) *CCSGameRules {
	if e == nil {
		return nil
	}
	return &CCSGameRules{Entity: e}
}

// BombDropped returns the CCSGameRules::m_bBombDropped property.
func (e *CCSGameRules) BombDropped() bool {
	v, _ := e.GetPropBool("CCSGameRules", "m_bBombDropped")
	return v
}

// SetBombDropped sets the CCSGameRules::m_bBombDropped property.
func (e *CCSGameRules) SetBombDropped(v bool) {
	e.SetPropBool("CCSGameRules", "m_bBombDropped", v)
}

// BombPlanted returns the CCSGameRules::m_bBombPlanted property.
func (e *CCSGameRules) BombPlanted() bool {
	v, _ := e.GetPropBool("CCSGameRules", "m_bBombPlanted")
	return v
}

// SetBombPlanted sets the CCSGameRules::m_bBombPlanted property.
func (e *CCSGameRules) SetBombPlanted(v bool) {
	e.SetPropBool("CCSGameRules", "m_bBombPlanted", v)
}

// FreezePeriod returns the CCSGameRules::m_bFreezePeriod property.
func (e *CCSGameRules) FreezePeriod() bool {
	v, _ := e.GetPropBool("CCSGameRules", "m_bFreezePeriod")
	return v
}

// SetFreezePeriod sets the CCSGameRules::m_bFreezePeriod property.
func (e *CCSGameRules) SetFreezePeriod(v bool) {
	e.SetPropBool("CCSGameRules", "m_bFreezePeriod", v)
}

// HasMatchStarted returns the CCSGameRules::m_bHasMatchStarted property.
func (e *CCSGameRules) HasMatchStarted() bool {
	v, _ := e.GetPropBool("CCSGameRules", "m_bHasMatchStarted")
	return v
}

// SetHasMatchStarted sets the CCSGameRules::m_bHasMatchStarted property.
func (e *CCSGameRules) SetHasMatchStarted(v bool) {
	e.SetPropBool("CCSGameRules", "m_bHasMatchStarted", v)
}

// WarmupPeriod returns the CCSGameRules::m_bWarmupPeriod property.
func (e *CCSGameRules) WarmupPeriod() bool {
	v, _ := e.GetPropBool("CCSGameRules", "m_bWarmupPeriod")
	return v
}

// SetWarmupPeriod sets the CCSGameRules::m_bWarmupPeriod property.
func (e *CCSGameRules) SetWarmupPeriod(v bool) {
	e.SetPropBool("CCSGameRules", "m_bWarmupPeriod", v)
}

// GamePhase returns the CCSGameRules::m_gamePhase property.
func (e *CCSGameRules) GamePhase() int32 {
	v, _ := e.GetPropInt("CCSGameRules", "m_gamePhase")
	return v
}

// SetGamePhase sets the CCSGameRules::m_gamePhase property.
func (e *CCSGameRules) SetGamePhase(v int32) {
	e.SetPropInt("CCSGameRules", "m_gamePhase", v)
}

// NumConsecutiveCTLoses returns the CCSGameRules::m_iNumConsecutiveCTLoses property.
func (e *CCSGameRules) NumConsecutiveCTLoses() int32 {
	v, _ := e.GetPropInt("CCSGameRules", "m_iNumConsecutiveCTLoses")
	return v
}

// SetNumConsecutiveCTLoses sets the CCSGameRules::m_iNumConsecutiveCTLoses property.
func (e *CCSGameRules) SetNumConsecutiveCTLoses(v int32) {
	e.SetPropInt("CCSGameRules", "m_iNumConsecutiveCTLoses", v)
}

// NumConsecutiveTerroristLoses returns the CCSGameRules::m_iNumConsecutiveTerroristLoses property.
func (e *CCSGameRules) NumConsecutiveTerroristLoses() int32 {
	v, _ := e.GetPropInt("CCSGameRules", "m_iNumConsecutiveTerroristLoses")
	return v
}

// SetNumConsecutiveTerroristLoses sets the CCSGameRules::m_iNumConsecutiveTerroristLoses property.
func (e *CCSGameRules) SetNumConsecutiveTerroristLoses(v int32) {
	e.SetPropInt("CCSGameRules", "m_iNumConsecutiveTerroristLoses", v)
}

// RoundTime returns the CCSGameRules::m_iRoundTime property.
func (e *CCSGameRules) RoundTime() int32 {
	v, _ := e.GetPropInt("CCSGameRules", "m_iRoundTime")
	return v
}

// SetRoundTime sets the CCSGameRules::m_iRoundTime property.
func (e *CCSGameRules) SetRoundTime(v int32) {
	e.SetPropInt("CCSGameRules", "m_iRoundTime", v)
}

// OvertimePlaying returns the CCSGameRules::m_nOvertimePlaying property.
func (e *CCSGameRules) OvertimePlaying() int32 {
	v, _ := e.GetPropInt("CCSGameRules", "m_nOvertimePlaying")
	return v
}

// SetOvertimePlaying sets the CCSGameRules::m_nOvertimePlaying property.
func (e *CCSGameRules) SetOvertimePlaying(v int32) {
	e.SetPropInt("CCSGameRules", "m_nOvertimePlaying", v)
}

// RoundsPlayedThisPhase returns the CCSGameRules::m_nRoundsPlayedThisPhase property.
func (e *CCSGameRules) RoundsPlayedThisPhase() int32 {
	v, _ := e.GetPropInt("CCSGameRules", "m_nRoundsPlayedThisPhase")
	return v
}

// SetRoundsPlayedThisPhase sets the CCSGameRules::m_nRoundsPlayedThisPhase property.
func (e *CCSGameRules) SetRoundsPlayedThisPhase(v int32) {
	e.SetPropInt("CCSGameRules", "m_nRoundsPlayedThisPhase", v)
}

// TotalRoundsPlayed returns the CCSGameRules::m_totalRoundsPlayed property.
func (e *CCSGameRules) TotalRoundsPlayed() int32 {
	v, _ := e.GetPropInt("CCSGameRules", "m_totalRoundsPlayed")
	return v
}

// SetTotalRoundsPlayed sets the CCSGameRules::m_totalRoundsPlayed property.
func (e *CCSGameRules) SetTotalRoundsPlayed(v int32) {
	e.SetPropInt("CCSGameRules", "m_totalRoundsPlayed", v)
}

// CCSPlayerController wraps an Entity with typed accessors for CCSPlayerController schema fields.
type CCSPlayerController struct {
	*gostrike.Entity
}

// NewCCSPlayerController wraps an existing Entity as a CCSPlayerController.
// Returns nil if the entity is nil.
func NewCCSPlayerController(e *gostrike.Entity) *CCSPlayerController {
	if e == nil {
		return nil
	}
	return &CCSPlayerController{Entity: e}
}

// CanControlObservedBot returns the CCSPlayerController::m_bCanControlObservedBot property.
func (e *CCSPlayerController) CanControlObservedBot() bool {
	v, _ := e.GetPropBool("CCSPlayerController", "m_bCanControlObservedBot")
	return v
}

// SetCanControlObservedBot sets the CCSPlayerController::m_bCanControlObservedBot property.
func (e *CCSPlayerController) SetCanControlObservedBot(v bool) {
	e.SetPropBool("CCSPlayerController", "m_bCanControlObservedBot", v)
}

// Connected returns the CCSPlayerController::m_bConnected property.
func (e *CCSPlayerController) Connected() bool {
	v, _ := e.GetPropBool("CCSPlayerController", "m_bConnected")
	return v
}

// SetConnected sets the CCSPlayerController::m_bConnected property.
func (e *CCSPlayerController) SetConnected(v bool) {
	e.SetPropBool("CCSPlayerController", "m_bConnected", v)
}

// PawnHasDefuser returns the CCSPlayerController::m_bPawnHasDefuser property.
func (e *CCSPlayerController) PawnHasDefuser() bool {
	v, _ := e.GetPropBool("CCSPlayerController", "m_bPawnHasDefuser")
	return v
}

// SetPawnHasDefuser sets the CCSPlayerController::m_bPawnHasDefuser property.
func (e *CCSPlayerController) SetPawnHasDefuser(v bool) {
	e.SetPropBool("CCSPlayerController", "m_bPawnHasDefuser", v)
}

// PawnHasHelmet returns the CCSPlayerController::m_bPawnHasHelmet property.
func (e *CCSPlayerController) PawnHasHelmet() bool {
	v, _ := e.GetPropBool("CCSPlayerController", "m_bPawnHasHelmet")
	return v
}

// SetPawnHasHelmet sets the CCSPlayerController::m_bPawnHasHelmet property.
func (e *CCSPlayerController) SetPawnHasHelmet(v bool) {
	e.SetPropBool("CCSPlayerController", "m_bPawnHasHelmet", v)
}

// PawnIsAlive returns the CCSPlayerController::m_bPawnIsAlive property.
func (e *CCSPlayerController) PawnIsAlive() bool {
	v, _ := e.GetPropBool("CCSPlayerController", "m_bPawnIsAlive")
	return v
}

// SetPawnIsAlive sets the CCSPlayerController::m_bPawnIsAlive property.
func (e *CCSPlayerController) SetPawnIsAlive(v bool) {
	e.SetPropBool("CCSPlayerController", "m_bPawnIsAlive", v)
}

// CompTeammateColor returns the CCSPlayerController::m_iCompTeammateColor property.
func (e *CCSPlayerController) CompTeammateColor() int32 {
	v, _ := e.GetPropInt("CCSPlayerController", "m_iCompTeammateColor")
	return v
}

// SetCompTeammateColor sets the CCSPlayerController::m_iCompTeammateColor property.
func (e *CCSPlayerController) SetCompTeammateColor(v int32) {
	e.SetPropInt("CCSPlayerController", "m_iCompTeammateColor", v)
}

// CompetitiveRankType returns the CCSPlayerController::m_iCompetitiveRankType property.
func (e *CCSPlayerController) CompetitiveRankType() int32 {
	v, _ := e.GetPropInt("CCSPlayerController", "m_iCompetitiveRankType")
	return v
}

// SetCompetitiveRankType sets the CCSPlayerController::m_iCompetitiveRankType property.
func (e *CCSPlayerController) SetCompetitiveRankType(v int32) {
	e.SetPropInt("CCSPlayerController", "m_iCompetitiveRankType", v)
}

// CompetitiveWins returns the CCSPlayerController::m_iCompetitiveWins property.
func (e *CCSPlayerController) CompetitiveWins() int32 {
	v, _ := e.GetPropInt("CCSPlayerController", "m_iCompetitiveWins")
	return v
}

// SetCompetitiveWins sets the CCSPlayerController::m_iCompetitiveWins property.
func (e *CCSPlayerController) SetCompetitiveWins(v int32) {
	e.SetPropInt("CCSPlayerController", "m_iCompetitiveWins", v)
}

// MVPs returns the CCSPlayerController::m_iMVPs property.
func (e *CCSPlayerController) MVPs() int32 {
	v, _ := e.GetPropInt("CCSPlayerController", "m_iMVPs")
	return v
}

// SetMVPs sets the CCSPlayerController::m_iMVPs property.
func (e *CCSPlayerController) SetMVPs(v int32) {
	e.SetPropInt("CCSPlayerController", "m_iMVPs", v)
}

// PawnArmor returns the CCSPlayerController::m_iPawnArmor property.
func (e *CCSPlayerController) PawnArmor() int32 {
	v, _ := e.GetPropInt("CCSPlayerController", "m_iPawnArmor")
	return v
}

// SetPawnArmor sets the CCSPlayerController::m_iPawnArmor property.
func (e *CCSPlayerController) SetPawnArmor(v int32) {
	e.SetPropInt("CCSPlayerController", "m_iPawnArmor", v)
}

// PawnHealth returns the CCSPlayerController::m_iPawnHealth property.
func (e *CCSPlayerController) PawnHealth() int32 {
	v, _ := e.GetPropInt("CCSPlayerController", "m_iPawnHealth")
	return v
}

// SetPawnHealth sets the CCSPlayerController::m_iPawnHealth property.
func (e *CCSPlayerController) SetPawnHealth(v int32) {
	e.SetPropInt("CCSPlayerController", "m_iPawnHealth", v)
}

// Ping returns the CCSPlayerController::m_iPing property.
func (e *CCSPlayerController) Ping() int32 {
	v, _ := e.GetPropInt("CCSPlayerController", "m_iPing")
	return v
}

// SetPing sets the CCSPlayerController::m_iPing property.
func (e *CCSPlayerController) SetPing(v int32) {
	e.SetPropInt("CCSPlayerController", "m_iPing", v)
}

// Score returns the CCSPlayerController::m_iScore property.
func (e *CCSPlayerController) Score() int32 {
	v, _ := e.GetPropInt("CCSPlayerController", "m_iScore")
	return v
}

// SetScore sets the CCSPlayerController::m_iScore property.
func (e *CCSPlayerController) SetScore(v int32) {
	e.SetPropInt("CCSPlayerController", "m_iScore", v)
}

// BotsControlledThisRound returns the CCSPlayerController::m_nBotsControlledThisRound property.
func (e *CCSPlayerController) BotsControlledThisRound() int32 {
	v, _ := e.GetPropInt("CCSPlayerController", "m_nBotsControlledThisRound")
	return v
}

// SetBotsControlledThisRound sets the CCSPlayerController::m_nBotsControlledThisRound property.
func (e *CCSPlayerController) SetBotsControlledThisRound(v int32) {
	e.SetPropInt("CCSPlayerController", "m_nBotsControlledThisRound", v)
}

// SanitizedPlayerName returns the CCSPlayerController::m_sSanitizedPlayerName property.
func (e *CCSPlayerController) SanitizedPlayerName() string {
	v, _ := e.GetPropString("CCSPlayerController", "m_sSanitizedPlayerName")
	return v
}

// SteamID returns the CCSPlayerController::m_steamID property.
func (e *CCSPlayerController) SteamID() int32 {
	v, _ := e.GetPropInt("CCSPlayerController", "m_steamID")
	return v
}

// SetSteamID sets the CCSPlayerController::m_steamID property.
func (e *CCSPlayerController) SetSteamID(v int32) {
	e.SetPropInt("CCSPlayerController", "m_steamID", v)
}

// CCSPlayerPawn wraps an Entity with typed accessors for CCSPlayerPawn schema fields.
type CCSPlayerPawn struct {
	*gostrike.Entity
}

// NewCCSPlayerPawn wraps an existing Entity as a CCSPlayerPawn.
// Returns nil if the entity is nil.
func NewCCSPlayerPawn(e *gostrike.Entity) *CCSPlayerPawn {
	if e == nil {
		return nil
	}
	return &CCSPlayerPawn{Entity: e}
}

// InNoDefuseArea returns the CCSPlayerPawn::m_bInNoDefuseArea property.
func (e *CCSPlayerPawn) InNoDefuseArea() bool {
	v, _ := e.GetPropBool("CCSPlayerPawn", "m_bInNoDefuseArea")
	return v
}

// SetInNoDefuseArea sets the CCSPlayerPawn::m_bInNoDefuseArea property.
func (e *CCSPlayerPawn) SetInNoDefuseArea(v bool) {
	e.SetPropBool("CCSPlayerPawn", "m_bInNoDefuseArea", v)
}

// IsBuyMenuOpen returns the CCSPlayerPawn::m_bIsBuyMenuOpen property.
func (e *CCSPlayerPawn) IsBuyMenuOpen() bool {
	v, _ := e.GetPropBool("CCSPlayerPawn", "m_bIsBuyMenuOpen")
	return v
}

// SetIsBuyMenuOpen sets the CCSPlayerPawn::m_bIsBuyMenuOpen property.
func (e *CCSPlayerPawn) SetIsBuyMenuOpen(v bool) {
	e.SetPropBool("CCSPlayerPawn", "m_bIsBuyMenuOpen", v)
}

// KilledByTaser returns the CCSPlayerPawn::m_bKilledByTaser property.
func (e *CCSPlayerPawn) KilledByTaser() bool {
	v, _ := e.GetPropBool("CCSPlayerPawn", "m_bKilledByTaser")
	return v
}

// SetKilledByTaser sets the CCSPlayerPawn::m_bKilledByTaser property.
func (e *CCSPlayerPawn) SetKilledByTaser(v bool) {
	e.SetPropBool("CCSPlayerPawn", "m_bKilledByTaser", v)
}

// PlayerState returns the CCSPlayerPawn::m_iPlayerState property.
func (e *CCSPlayerPawn) PlayerState() int32 {
	v, _ := e.GetPropInt("CCSPlayerPawn", "m_iPlayerState")
	return v
}

// SetPlayerState sets the CCSPlayerPawn::m_iPlayerState property.
func (e *CCSPlayerPawn) SetPlayerState(v int32) {
	e.SetPropInt("CCSPlayerPawn", "m_iPlayerState", v)
}

// WhichBombZone returns the CCSPlayerPawn::m_nWhichBombZone property.
func (e *CCSPlayerPawn) WhichBombZone() int32 {
	v, _ := e.GetPropInt("CCSPlayerPawn", "m_nWhichBombZone")
	return v
}

// SetWhichBombZone sets the CCSPlayerPawn::m_nWhichBombZone property.
func (e *CCSPlayerPawn) SetWhichBombZone(v int32) {
	e.SetPropInt("CCSPlayerPawn", "m_nWhichBombZone", v)
}

// CCSPlayerPawnBase wraps an Entity with typed accessors for CCSPlayerPawnBase schema fields.
type CCSPlayerPawnBase struct {
	*gostrike.Entity
}

// NewCCSPlayerPawnBase wraps an existing Entity as a CCSPlayerPawnBase.
// Returns nil if the entity is nil.
func NewCCSPlayerPawnBase(e *gostrike.Entity) *CCSPlayerPawnBase {
	if e == nil {
		return nil
	}
	return &CCSPlayerPawnBase{Entity: e}
}

// ArmorValue returns the CCSPlayerPawnBase::m_ArmorValue property.
func (e *CCSPlayerPawnBase) ArmorValue() int32 {
	v, _ := e.GetPropInt("CCSPlayerPawnBase", "m_ArmorValue")
	return v
}

// SetArmorValue sets the CCSPlayerPawnBase::m_ArmorValue property.
func (e *CCSPlayerPawnBase) SetArmorValue(v int32) {
	e.SetPropInt("CCSPlayerPawnBase", "m_ArmorValue", v)
}

// HasHeavyArmor returns the CCSPlayerPawnBase::m_bHasHeavyArmor property.
func (e *CCSPlayerPawnBase) HasHeavyArmor() bool {
	v, _ := e.GetPropBool("CCSPlayerPawnBase", "m_bHasHeavyArmor")
	return v
}

// SetHasHeavyArmor sets the CCSPlayerPawnBase::m_bHasHeavyArmor property.
func (e *CCSPlayerPawnBase) SetHasHeavyArmor(v bool) {
	e.SetPropBool("CCSPlayerPawnBase", "m_bHasHeavyArmor", v)
}

// HasHelmet returns the CCSPlayerPawnBase::m_bHasHelmet property.
func (e *CCSPlayerPawnBase) HasHelmet() bool {
	v, _ := e.GetPropBool("CCSPlayerPawnBase", "m_bHasHelmet")
	return v
}

// SetHasHelmet sets the CCSPlayerPawnBase::m_bHasHelmet property.
func (e *CCSPlayerPawnBase) SetHasHelmet(v bool) {
	e.SetPropBool("CCSPlayerPawnBase", "m_bHasHelmet", v)
}

// InBombZone returns the CCSPlayerPawnBase::m_bInBombZone property.
func (e *CCSPlayerPawnBase) InBombZone() bool {
	v, _ := e.GetPropBool("CCSPlayerPawnBase", "m_bInBombZone")
	return v
}

// SetInBombZone sets the CCSPlayerPawnBase::m_bInBombZone property.
func (e *CCSPlayerPawnBase) SetInBombZone(v bool) {
	e.SetPropBool("CCSPlayerPawnBase", "m_bInBombZone", v)
}

// InBuyZone returns the CCSPlayerPawnBase::m_bInBuyZone property.
func (e *CCSPlayerPawnBase) InBuyZone() bool {
	v, _ := e.GetPropBool("CCSPlayerPawnBase", "m_bInBuyZone")
	return v
}

// SetInBuyZone sets the CCSPlayerPawnBase::m_bInBuyZone property.
func (e *CCSPlayerPawnBase) SetInBuyZone(v bool) {
	e.SetPropBool("CCSPlayerPawnBase", "m_bInBuyZone", v)
}

// IsDefusing returns the CCSPlayerPawnBase::m_bIsDefusing property.
func (e *CCSPlayerPawnBase) IsDefusing() bool {
	v, _ := e.GetPropBool("CCSPlayerPawnBase", "m_bIsDefusing")
	return v
}

// SetIsDefusing sets the CCSPlayerPawnBase::m_bIsDefusing property.
func (e *CCSPlayerPawnBase) SetIsDefusing(v bool) {
	e.SetPropBool("CCSPlayerPawnBase", "m_bIsDefusing", v)
}

// IsGrabbingHostage returns the CCSPlayerPawnBase::m_bIsGrabbingHostage property.
func (e *CCSPlayerPawnBase) IsGrabbingHostage() bool {
	v, _ := e.GetPropBool("CCSPlayerPawnBase", "m_bIsGrabbingHostage")
	return v
}

// SetIsGrabbingHostage sets the CCSPlayerPawnBase::m_bIsGrabbingHostage property.
func (e *CCSPlayerPawnBase) SetIsGrabbingHostage(v bool) {
	e.SetPropBool("CCSPlayerPawnBase", "m_bIsGrabbingHostage", v)
}

// IsScoped returns the CCSPlayerPawnBase::m_bIsScoped property.
func (e *CCSPlayerPawnBase) IsScoped() bool {
	v, _ := e.GetPropBool("CCSPlayerPawnBase", "m_bIsScoped")
	return v
}

// SetIsScoped sets the CCSPlayerPawnBase::m_bIsScoped property.
func (e *CCSPlayerPawnBase) SetIsScoped(v bool) {
	e.SetPropBool("CCSPlayerPawnBase", "m_bIsScoped", v)
}

// IsWalking returns the CCSPlayerPawnBase::m_bIsWalking property.
func (e *CCSPlayerPawnBase) IsWalking() bool {
	v, _ := e.GetPropBool("CCSPlayerPawnBase", "m_bIsWalking")
	return v
}

// SetIsWalking sets the CCSPlayerPawnBase::m_bIsWalking property.
func (e *CCSPlayerPawnBase) SetIsWalking(v bool) {
	e.SetPropBool("CCSPlayerPawnBase", "m_bIsWalking", v)
}

// WaitForNoAttack returns the CCSPlayerPawnBase::m_bWaitForNoAttack property.
func (e *CCSPlayerPawnBase) WaitForNoAttack() bool {
	v, _ := e.GetPropBool("CCSPlayerPawnBase", "m_bWaitForNoAttack")
	return v
}

// SetWaitForNoAttack sets the CCSPlayerPawnBase::m_bWaitForNoAttack property.
func (e *CCSPlayerPawnBase) SetWaitForNoAttack(v bool) {
	e.SetPropBool("CCSPlayerPawnBase", "m_bWaitForNoAttack", v)
}

// FlashDuration returns the CCSPlayerPawnBase::m_flFlashDuration property.
func (e *CCSPlayerPawnBase) FlashDuration() float32 {
	v, _ := e.GetPropFloat("CCSPlayerPawnBase", "m_flFlashDuration")
	return v
}

// SetFlashDuration sets the CCSPlayerPawnBase::m_flFlashDuration property.
func (e *CCSPlayerPawnBase) SetFlashDuration(v float32) {
	e.SetPropFloat("CCSPlayerPawnBase", "m_flFlashDuration", v)
}

// FlashMaxAlpha returns the CCSPlayerPawnBase::m_flFlashMaxAlpha property.
func (e *CCSPlayerPawnBase) FlashMaxAlpha() float32 {
	v, _ := e.GetPropFloat("CCSPlayerPawnBase", "m_flFlashMaxAlpha")
	return v
}

// SetFlashMaxAlpha sets the CCSPlayerPawnBase::m_flFlashMaxAlpha property.
func (e *CCSPlayerPawnBase) SetFlashMaxAlpha(v float32) {
	e.SetPropFloat("CCSPlayerPawnBase", "m_flFlashMaxAlpha", v)
}

// VelocityModifier returns the CCSPlayerPawnBase::m_flVelocityModifier property.
func (e *CCSPlayerPawnBase) VelocityModifier() float32 {
	v, _ := e.GetPropFloat("CCSPlayerPawnBase", "m_flVelocityModifier")
	return v
}

// SetVelocityModifier sets the CCSPlayerPawnBase::m_flVelocityModifier property.
func (e *CCSPlayerPawnBase) SetVelocityModifier(v float32) {
	e.SetPropFloat("CCSPlayerPawnBase", "m_flVelocityModifier", v)
}

// ShotsFired returns the CCSPlayerPawnBase::m_iShotsFired property.
func (e *CCSPlayerPawnBase) ShotsFired() int32 {
	v, _ := e.GetPropInt("CCSPlayerPawnBase", "m_iShotsFired")
	return v
}

// SetShotsFired sets the CCSPlayerPawnBase::m_iShotsFired property.
func (e *CCSPlayerPawnBase) SetShotsFired(v int32) {
	e.SetPropInt("CCSPlayerPawnBase", "m_iShotsFired", v)
}

// CCSWeaponBase wraps an Entity with typed accessors for CCSWeaponBase schema fields.
type CCSWeaponBase struct {
	*gostrike.Entity
}

// NewCCSWeaponBase wraps an existing Entity as a CCSWeaponBase.
// Returns nil if the entity is nil.
func NewCCSWeaponBase(e *gostrike.Entity) *CCSWeaponBase {
	if e == nil {
		return nil
	}
	return &CCSWeaponBase{Entity: e}
}

// BurstMode returns the CCSWeaponBase::m_bBurstMode property.
func (e *CCSWeaponBase) BurstMode() bool {
	v, _ := e.GetPropBool("CCSWeaponBase", "m_bBurstMode")
	return v
}

// SetBurstMode sets the CCSWeaponBase::m_bBurstMode property.
func (e *CCSWeaponBase) SetBurstMode(v bool) {
	e.SetPropBool("CCSWeaponBase", "m_bBurstMode", v)
}

// InReload returns the CCSWeaponBase::m_bInReload property.
func (e *CCSWeaponBase) InReload() bool {
	v, _ := e.GetPropBool("CCSWeaponBase", "m_bInReload")
	return v
}

// SetInReload sets the CCSWeaponBase::m_bInReload property.
func (e *CCSWeaponBase) SetInReload(v bool) {
	e.SetPropBool("CCSWeaponBase", "m_bInReload", v)
}

// RecoilIndex returns the CCSWeaponBase::m_flRecoilIndex property.
func (e *CCSWeaponBase) RecoilIndex() float32 {
	v, _ := e.GetPropFloat("CCSWeaponBase", "m_flRecoilIndex")
	return v
}

// SetRecoilIndex sets the CCSWeaponBase::m_flRecoilIndex property.
func (e *CCSWeaponBase) SetRecoilIndex(v float32) {
	e.SetPropFloat("CCSWeaponBase", "m_flRecoilIndex", v)
}

// WeaponMode returns the CCSWeaponBase::m_weaponMode property.
func (e *CCSWeaponBase) WeaponMode() int32 {
	v, _ := e.GetPropInt("CCSWeaponBase", "m_weaponMode")
	return v
}

// SetWeaponMode sets the CCSWeaponBase::m_weaponMode property.
func (e *CCSWeaponBase) SetWeaponMode(v int32) {
	e.SetPropInt("CCSWeaponBase", "m_weaponMode", v)
}
